export { default as authRoutes } from "./auth.routes";
export { default as contactRoutes } from "./contact.routes";
export { default as profileRoutes } from "./profile.routes";
export { default as categoriesRoutes } from "./categories.routes";
export { default as infoRoutes } from "./info.routes";
export { default as ordersRoutes } from "./orders.routes";
export { default as appointmentRoutes } from "./appointment.routes";
export { default as productsRoutes } from "./products.routes";
export { default as faqRoutes } from "./faq.routes";
